### ISSUE TITLE
Import/export JSON for backup/restore

### ISSUE THREAD

**Issue by ashchan** [ashchan/returns#43]
## TODO

- [x] export
- [ ] import
- [x] localization

* Since CloudKit sync will not be implemented this would be the option to move data cross devices
* It also allows to do regular backups to avoid data loss

Note CSV import might not be easy to do. The original excel/gdoc files don't have a good CSV output.

Instead of CSV, the format would be JSON to simply represent CoreData data.

**Comment by passwii** [comment]
That's will be great to have a backup option.

**Comment by ashchan** [comment]
@passwii i’ll implement that soon.
