### ISSUE TITLE
10,000 return?

### ISSUE THREAD

**Issue by I-Valchev** [ashchan/returns#64]
The app seems to assume some sort of 10,000 investment baseline. I highly doubt this at first glance random number will help. For me, I do know that it gives me incorrect calculations for 1+ years of return.

Let's make a way to disable that?

**Comment by ashchan** [comment]
> I do know that it gives me incorrect calculations for 1+ years of return.

Can you explain why the calculation is incorrect?

Please note it’s not saying everyone has 10k at the beginning. It’s saying for what the balance is trending based to 10k. So for example if I have initial deposit of 5000, and the return is 10% at the moment, the chart will show 10000 to 11000. The 10k number is not important here, it could even be just 1.0 $.

**Comment by I-Valchev** [comment]
I don't understand this, to be honest. For me this is a totally irrelevant number, what I am interested in while using this is to see the charts, automatically calculated return rates, and "how much did I earn this month".

This last part, which is growth, is obscured by the 10,000 trending idea.


If you have 5,000 and earned 10%, I would assume the app should show a line from 5,000 to 5,500. But showing a graph from 10,000 to 11,000 is confusing and actually misleading, because in effect your income shows as doubled.

**Comment by I-Valchev** [comment]
Also, happy to share with you the calculations in a place less public than here :-)

**Comment by ashchan** [comment]
@I-Valchev 

The app features were highly replicated from [A Returns Spreadsheet for Bogleheads](https://www.bogleheads.org/forum/viewtopic.php?t=150025&sid=8e25a3a91b1fbbedfb9e5b2b0738105a). The growth-of-$10,000 chart doesn't rely on the '$10,000' number, but is just a way to illustrated the portfolio return (which removes the effect of contributions and withdrawals), so it can be used to compare with other plain returns.

You can simply ignore the number itself, and look at the chart and trend only.

Sorry for replying late. It's summer holiday and my family has been on camp vacation I got away for a while.

**Comment by I-Valchev** [comment]
No problem for the reply time, I understand thanks. 👍
