### ISSUE TITLE
issue: Account page: cell board doesn't move when dragging

### ISSUE THREAD

**Issue by ThaddeusJiang** [ashchan/returns#65]
![CleanShot 2023-12-04 at 12 01 49](https://github.com/ashchan/returns/assets/17308201/08758e91-e8d1-4061-a1f7-d4d8eef107ed)

**Comment by ashchan** [comment]
Known issue from the very first release. Will take a look and see if it's worthy fixing at year end :)

**Comment by ashchan** [comment]
There're still some refreshing issues but I don't think they're worthy fixing - the table is `NSTableView` contained in a `SwiftUI` view, required for performance but difficult to control fully.
