### ISSUE TITLE
Bug: The year 2024 is automatically changed to 6.

### ISSUE THREAD

**Issue by ThaddeusJiang** [ashchan/returns#66]
my input: 2024

display after saved: 6

<img width="923" alt="IMG_7399" src="https://github.com/user-attachments/assets/7b5fa93e-1e5c-42d6-9e8c-ca5fe7d87169">

**Comment by ashchan** [comment]
@ThaddeusJiang Can you show your language & region settings? Below is mine. Thanks.
![CleanShot 2024-11-22 at 09 14 39@2x](https://github.com/user-attachments/assets/89bdb0f0-402c-44c2-965e-0eb2ac3bed02)

**Comment by ThaddeusJiang** [comment]
![CleanShot 0006-11-22 at 17 45 48](https://github.com/user-attachments/assets/fe905fcc-c2de-4b96-87a8-7fb1437c909f)

**Comment by ashchan** [comment]
@ThaddeusJiang Thanks. I'll debug and try to fix this when I have time.

**Comment by ashchan** [comment]
A new version (1.5) has been updated and should appear in the App Store soon. Please check and see if it fixes the calendar problem.
